//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadohinControl11.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSchool
    {
        public ClassSchool()
        {
            this.AccountigMaculatura = new HashSet<AccountigMaculatura>();
        }
    
        public int id { get; set; }
        public Nullable<int> idType { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<AccountigMaculatura> AccountigMaculatura { get; set; }
        public virtual TypeClass TypeClass { get; set; }
    }
}
